### ISSUE TITLE
内容区太窄了

### ISSUE THREAD

**Issue by yaoyi2008** [FishionYu/typora-inside-theme#1]
能否加宽下内容区大小，或者在哪里可以自己去设置呀？

**Comment by yaoyi2008** [comment]
我找到了，还得谢谢大佬的主题，很nice！
```css
#write {
    max-width: 600px;
}
```
